# Generated by Django 3.1.6 on 2021-03-19 17:47

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to=job.models.upload_image),
        ),
    ]
