# Generated by Django 3.1.6 on 2021-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210319_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('webSite', models.URLField()),
                ('cv', models.FileField(upload_to='Apply/')),
                ('cover_letter', models.TextField(max_length=500)),
            ],
        ),
    ]
