# Generated by Django 3.1.6 on 2021-03-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='apply_Work', to='job.work'),
            preserve_default=False,
        ),
    ]
